### ISSUE TITLE
小火箭的格式好像不对

### ISSUE THREAD

**Issue by Silent-wqh** [xi11-ov/xi#1]
小火箭好像不支持这种 yaml 样式的引用，我使用 RULE-SET 引用后经过测试规则不生效。
我感觉应该按照类似这样的格式写 https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Shadowrocket/WeChat/WeChat.list

**Comment by xi11-ov** [comment]
感谢你的宝贵反馈，通过你提供的链接文档作为参考已进行修改，经测试使用RUILE-SET已分流成功。
